#!/usr/bin/env bash
# Copy this project's Claude Code transcript into sessions/<date>-<slug>/ and render it readable.
#   .claude/archive-session.sh <slug>          e.g. .claude/archive-session.sh m1-parser
# Run it from the repo root. Check the result for emails, absolute paths, keys and scraped
# third-party content BEFORE committing, and confirm the repo's visibility (CONSTITUTION §1, §6).
set -euo pipefail

SLUG="${1:-session}"
ROOT="$(pwd)"
PROJECTS="$HOME/.claude/projects"
# Claude Code names the folder after the path with every non-alphanumeric character turned into '-'
# ("/home/me/Personal projects/X" -> "-home-me-Personal-projects-X").
SRC="$PROJECTS/$(printf '%s' "$ROOT" | sed 's|[^a-zA-Z0-9]|-|g')"
if [ ! -d "$SRC" ]; then
  # Fallback: find the folder whose transcripts record this repo as their working directory.
  SRC="$(python3 - "$PROJECTS" "$ROOT" <<'PY'
import json, os, sys
base, root = sys.argv[1], sys.argv[2]
for d in sorted(os.listdir(base)) if os.path.isdir(base) else []:
    p = os.path.join(base, d)
    for f in (x for x in os.listdir(p) if x.endswith('.jsonl')):
        try:
            for line in open(os.path.join(p, f), encoding='utf-8'):
                if json.loads(line).get('cwd') == root:
                    print(p); sys.exit(0)
        except Exception:
            pass
PY
)"
fi
[ -n "$SRC" ] && [ -d "$SRC" ] || { echo "No Claude Code transcripts found for $ROOT under $PROJECTS"; exit 1; }

LATEST="$(ls -t "$SRC"/*.jsonl 2>/dev/null | head -1)" || true
[ -n "${LATEST:-}" ] || { echo "No .jsonl transcript found in $SRC"; exit 1; }

DEST="sessions/$(date +%F)-$SLUG"
mkdir -p "$DEST/raw"
cp "$LATEST" "$DEST/raw/session.jsonl"
BASE="${LATEST%.jsonl}"
if [ -d "$BASE/subagents" ]; then cp "$BASE/subagents/"* "$DEST/raw/" 2>/dev/null || true; fi

python3 - "$DEST/raw/session.jsonl" "$DEST/transcript.md" <<'PY'
import json, sys, io
LIMIT = 1800
src, out = sys.argv[1], sys.argv[2]
def clip(s, n=LIMIT):
    s = s if isinstance(s, str) else json.dumps(s, ensure_ascii=False, indent=2)
    return s if len(s) <= n else s[:n] + f"\n... [clipped, {len(s)-n} more chars]"
parts, nu, na, nt = ["# Session transcript\n", "Generated by `.claude/archive-session.sh`. Tool payloads are clipped; `raw/` has everything.\n"], 0, 0, 0
for line in io.open(src, encoding='utf-8'):
    line = line.strip()
    if not line: continue
    try: d = json.loads(line)
    except Exception: continue
    t, m = d.get('type'), d.get('message')
    if not isinstance(m, dict): continue
    c = m.get('content')
    if t == 'user':
        if isinstance(c, str) and c.strip():
            nu += 1; parts.append(f"\n---\n\n## User\n\n{c.strip()}\n")
        elif isinstance(c, list):
            for b in c:
                if isinstance(b, dict) and b.get('type') == 'tool_result':
                    parts.append("\n**tool result**\n\n````\n" + clip(b.get('content', '')) + "\n````\n")
    elif t == 'assistant' and isinstance(c, list):
        na += 1
        for b in c:
            if not isinstance(b, dict): continue
            if b.get('type') == 'text' and b.get('text', '').strip():
                parts.append(f"\n## Assistant\n\n{b['text'].strip()}\n")
            elif b.get('type') == 'tool_use':
                nt += 1
                parts.append(f"\n**tool: {b.get('name')}**\n\n````json\n" + clip(b.get('input', {})) + "\n````\n")
parts.insert(2, f"\n**{nu} user messages · {na} assistant replies · {nt} tool calls**\n")
io.open(out, 'w', encoding='utf-8').write("\n".join(parts))
print(f"wrote {out}")
PY

echo
echo "Archived to $DEST"
echo "Before committing, scan it:"
echo "  grep -nEi '@[a-z0-9.-]+\\.[a-z]{2,}|sk-[A-Za-z0-9_-]{20,}|/home/[a-z]+|/Users/[a-z]+' $DEST/transcript.md | head"
